{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default page_uri_suffix=false()
         left_max=3
         right_max=3}
{default name=ViewParameter
         page_uri_suffix=false()
         left_max=$left_max
         right_max=$right_max}

{let page_count=int( ceil( div( $item_count,$item_limit ) ) )
     current_page=min($:page_count,int( ceil( div( first_set( $view_parameters.offset, 0),$item_limit ) ) ) )
     item_previous=sub( mul( $:current_page, $item_limit ),$item_limit ) item_next=sum( mul( $:current_page, $item_limit ), $item_limit )
     left_length=min($ViewParameter:current_page,$:left_max)
     right_length=max(min(sub($ViewParameter:page_count,$ViewParameter:current_page,1),$:right_max),0)
     view_parameter_text=""
     offset_text=eq( ezini( 'ControlSettings', 'AllowUserVariables', 'template.ini' ), 'true' )|choose( '/offset/', '/(offset)/' )}
{* Create view parameter text with the exception of offset *}
{section loop=$view_parameters}

{section-exclude match=$:key|eq('offset')}

{section-exclude match=$:item|eq('')}
    {set view_parameter_text=concat($:view_parameter_text,'/(',$:key,')/',$:item)}
{/section}


{section show=$:page_count|gt(1)}
    <div class="u-flex u-flexWrap u-sm-flexJustifyCenter u-md-flexJustifyCenter u-lg-flexJustifyCenter">


        {switch match=$:item_previous|lt(0) }
        {case match=0}
            <div class="FlexItem"><a class="Button Button--info"
                        href={concat($page_uri,$:item_previous|gt(0)|choose('',concat($:offset_text,$:item_previous)),$:view_parameter_text,$page_uri_suffix)|ezurl}><span
                            class="text">&laquo;&nbsp;{"Previous"|i18n("design/admin/navigator")}</span></a></div>
        {/case}
        {case}
            <div class="disabled FlexItem"><span
                        class="text disabled Button Button--info">&laquo;&nbsp;{"Previous"|i18n("design/admin/navigator")}</span></div>
        {/case}
        {/switch}


        {if $:current_page|gt($:left_max)}
            <div class="FlexItem"><a href={concat($page_uri,$:view_parameter_text,$page_uri_suffix)|ezurl}>1</a></div>
            {if sub($:current_page,$:left_length)|gt(1)}
                <div class="other FlexItem"><a class="Button Button--info">...</a></div>
            {/if}
        {/if}

        {section loop=$:left_length}
            {let page_offset=sum(sub($ViewParameter:current_page,$ViewParameter:left_length),$:index)}
                <div class="FlexItem"><a class="Button Button--info" href={concat($page_uri,$:page_offset|gt(0)|choose('',concat($:offset_text,mul($:page_offset,$item_limit))),$ViewParameter:view_parameter_text,$page_uri_suffix)|ezurl}>{$:page_offset|inc}</a>
                    </div>
            {/let}
        {/section}

        <div class="active FlexItem"><span class="Button">{$:current_page|inc}</span></div>

        {section loop=$:right_length}
            {let page_offset=sum($ViewParameter:current_page,1,$:index)}
                <div class="FlexItem"><a class="Button Button--info" class="next"
                        href={concat($page_uri,$:page_offset|gt(0)|choose('',concat($:offset_text,mul($:page_offset,$item_limit))),$ViewParameter:view_parameter_text,$page_uri_suffix)|ezurl}>{$:page_offset|inc}</a>
                    </div>
            {/let}
        {/section}

        {if $:page_count|gt(sum($:current_page,$:right_max,1))}
            {if sum($:current_page,$:right_max,2)|lt($:page_count)}
                <div class="other FlexItem"><span class="Button Button--info">...</span></div>
            {/if}
            <div class="FlexItem">
                <a class="Button Button--info" href={concat($page_uri,$:page_count|dec|gt(0)|choose('',concat($:offset_text,mul($:page_count|dec,$item_limit))),$:view_parameter_text,$page_uri_suffix)|ezurl}>{$:page_count}</a>
            </div>
        {/if}

        {switch match=$:item_next|lt($item_count)}
        {case match=1}
            <div class="FlexItem"><a class="Button Button--info" href={concat($page_uri,$:offset_text,$:item_next,$:view_parameter_text,$page_uri_suffix)|ezurl}><span
                            class="text">{"Next"|i18n("design/admin/navigator")}&nbsp;&raquo;</span></a></div>
        {/case}
        {case}
            <div class="disabled FlexItem"><span class="text disabled Button Button--info">{"Next"|i18n("design/admin/navigator")}
                    &nbsp;&raquo;</span></div>
        {/case}
        {/switch}


    </div>
{/section}

{/let}
{/default}
{/default}

