{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let handlers=$handler.collaboration_handlers
selection=$handler.collaboration_selections}

  <div class="contentheader">
    <h2>{"Collaboration notification"|i18n("design/standard/notification/collaboration")}</h2>
  </div>
  <p>{"Choose which collaboration items you want to get notifications for."|i18n("design/standard/notification/collaboration")}</p>

  <input type="hidden" name="CollaborationHandlerSelection" value="1" />

  <table border="0" cellspacing="0" cellpadding="0">
    {foreach $handlers as $handler_item}

      {if $handler_item.info.type-identifier|eq('openpasensor')}{skip}{/if}

      {def $types = $handler_item.notification_types}
      {if and($types, $types|gt(0))}
        {if is_array($types)}
          <tr>
            <td colspan="2">
              {$handler_item.info.type-name|wash}
            </td>
          </tr>
          {foreach $types as $type}
            <tr>
              <td>
                <input type="checkbox" name="CollaborationHandlerSelection_{$handler.id_string}[]"
                       value="{$handler_item.info.type-identifier}_{$type.value}"
                       {if $selection|contains(concat($handler_item.info.type-identifier,'_',$handler_item.value))}checked="checked"{/if} />
              </td>
              <td>
                {$type.name|wash}
              </td>
            </tr>
          {/foreach}
        {else}
          <tr>
            <td>
              <input type="checkbox" name="CollaborationHandlerSelection_{$handler.id_string}[]"
                     value="{$handler_item.info.type-identifier}"
                     {if $selection|contains($handler_item.info.type-identifier)}checked="checked"{/if} />
            </td>
            <td>
              {$handler_item.info.type-name|wash}
            </td>
          </tr>
        {/if}
      {/if}
      {undef $types}
    {/foreach}
  </table>

{/let}
