{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* Mirko 26.02.2015 - aggiunto div content-view-line *}
{default node_name=$object.main_node.name node_url=$object.main_node.url_alias}
	<div class="content-view-line"><i class="fa fa-file"></i> {$object.class_name}: {if $node_url}<a href={$node_url|ezurl}>{/if}{$node_name|wash}{if $node_url}</a>{/if}</div>
{/default}